version: '3'
services:
  web:
    build: ./web
    container_name: vesputi_web
    command: 'rails s -b 0.0.0.0'
    volumes:
      - ./web:/web
    ports:
      - '3000:3000'
      - '3035:3035'
    # entrypoint: /bin/sh
    # stdin_open: true
    # tty: true
  db:
    image: postgis/postgis
    container_name: vesputi_db
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"